"""
Independent script: Redraw Variable Heatmap
Directly copy the save_variable_heatmaps_by_model function from the original script to ensure completely identical output.

Usage:
    python redraw_variable_heatmap.py
    python redraw_variable_heatmap.py --run_dir ml_results/run_20260206_234650

Arguments:
    --run_dir: Path to the executed run directory (Default: ml_results/run_20260206_234650)
    --target: Name of the dependent variable column (Default: Metastasis)
    --top_n: Number of features to display (Default: 20, identical to the original script)
    --models: Specify models to plot (comma-separated, e.g., LR,RF,XGB; Default: all available models)
    --output_dir: Directory for saving output figures (Default: run_dir/fig_new)
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any

import joblib
import matplotlib
import matplotlib.colors
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scipy.sparse as sp
from sklearn.base import BaseEstimator, TransformerMixin


# ============ Custom Classes (Consistent with original script for model loading) ============
class ColumnSelector(TransformerMixin, BaseEstimator):
    """Feature column selector"""
    def __init__(self, indices: np.ndarray):
        self.indices = np.asarray(indices, dtype=int)

    def fit(self, X: Any, y: Any = None):
        return self

    def transform(self, X: Any):
        if sp.issparse(X):
            return X[:, self.indices]
        return np.asarray(X)[:, self.indices]


class ToDense(TransformerMixin, BaseEstimator):
    """Transform sparse matrix to dense matrix"""
    def fit(self, X: Any, y: Any = None):
        return self

    def transform(self, X: Any):
        if sp.issparse(X):
            return X.toarray()
        return np.asarray(X)


# ============ Constants Definition ============
DEMOGRAPHIC_COLUMNS_EXCLUDE = ["Sex"]

# ============ Font Size Configuration (Adjustable manually) ============
FONTSIZE_FEATURE_LABEL = 12      # Font size for feature labels on the right side of the heatmap
FONTSIZE_ANNOT_LABEL = 12         # Font size for annotation row labels (Predicted value/Outcome/Group)
FONTSIZE_LEGEND_TITLE = 12       # Font size for Legend titles (variable names)
FONTSIZE_LEGEND_TEXT = 10         # Font size for labels next to Legend color boxes
FONTSIZE_COLORBAR_TICK = 10       # Font size for colorbar tick labels of continuous variables


# ============ Helper Functions ============
def _ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def _safe_float32_matrix(X: Any) -> Any:
    if sp.issparse(X):
        X = X.tocsr(copy=False)
        return X.astype(np.float32) if X.dtype != np.float32 else X
    X = np.asarray(X)
    return X.astype(np.float32) if X.dtype != np.float32 else X


def get_feature_names(preprocessor) -> list[str]:
    try:
        names = preprocessor.get_feature_names_out()
        return [str(x) for x in names]
    except Exception:
        return []


def _clean_display_feature_names(names: list[str]) -> list[str]:
    """Remove sklearn prefixes (e.g., num__, cat__)"""
    out: list[str] = []
    for n in names:
        if "__" in n:
            n = n.split("__", 1)[-1]
        out.append(n)
    return out


# ============ Helper Function: Parse preprocessed feature name → raw column name ============
def _parse_internal_feature_name(
    feature_name: str, raw_columns: list[str]
) -> tuple[str | None, str | None, bool]:
    """Parse feature names generated by sklearn ColumnTransformer.

    Returns (raw_column_name, category_value_str, is_categorical)
    Examples:
        'num__CEA'               → ('CEA', None, False)
        'cat__Carcinoma nodule_0' → ('Carcinoma nodule', '0', True)
        'cat__T stage_T1-T2'     → ('T stage', 'T1-T2', True)
    """
    if feature_name.startswith("num__"):
        col = feature_name[5:]
        return (col, None, False) if col in raw_columns else (None, None, False)
    if feature_name.startswith("cat__"):
        rest = feature_name[5:]
        # Match by raw column name length from longest to shortest to prevent underscore ambiguity
        for col in sorted(raw_columns, key=len, reverse=True):
            if rest.startswith(col + "_"):
                return col, rest[len(col) + 1:], True
            if rest == col:
                return col, None, True
        # Fallback: split from the right side once
        parts = rest.rsplit("_", 1)
        if len(parts) == 2:
            return (parts[0], parts[1], True) if parts[0] in raw_columns else (None, None, True)
        return (None, None, True)
    return (None, None, False)


def _convert_cat_val(s: str):
    """Convert categorical value string to proper type (int > float > str)."""
    try:
        return int(s)
    except (ValueError, TypeError):
        try:
            return float(s)
        except (ValueError, TypeError):
            return s


# ============ Original save_variable_heatmaps_by_model Function (Fully Copied) ============
def save_variable_heatmaps_by_model(
    out_dir: Path,
    X_train: Any,
    X_test: Any,
    y_train: np.ndarray,
    y_test: np.ndarray,
    y_proba_train_by_model: dict[str, np.ndarray],
    y_proba_test_by_model: dict[str, np.ndarray],
    importance_tables: dict[str, pd.DataFrame],
    top_n: int | None = None,
    X_external: Any | None = None,
    y_external: np.ndarray | None = None,
    y_proba_external_by_model: dict[str, np.ndarray] | None = None,
    raw_df: pd.DataFrame | None = None,
) -> None:
    """Output an individual 'variable heatmap' for each model, imitating the style of the sample figure:

    - Rows: Features used in the model (Displays all features by default; truncates to Top-N if top_n is specified)
    - Columns: Samples (Concatenation of training set + test set + external validation set)
    - Feature labels are shown on the right side
    - Three extra annotation rows: Predicted value / Outcome / Group
    - Bottom legend section: Vertical colorbar per variable, organized in a grid layout

    Note: To avoid scaling differences across variables affecting color presentation,
    each feature row is independently normalized to [0,1] via min-max scaling.
    """
    if not importance_tables:
        print("[FIG] No importance tables; skip variable heatmaps.")
        return

    _ensure_dir(out_dir)

    # Check if external validation set exists
    has_external = (
        X_external is not None
        and y_external is not None
        and y_proba_external_by_model is not None
        and len(y_external) > 0
    )

    # Concatenate samples
    if has_external:
        if sp.issparse(X_train) or sp.issparse(X_test) or sp.issparse(X_external):
            X_all = sp.vstack([X_train, X_test, X_external], format="csr")
        else:
            X_all = np.vstack([np.asarray(X_train), np.asarray(X_test), np.asarray(X_external)])
        y_all = np.concatenate([
            np.asarray(y_train).ravel(),
            np.asarray(y_test).ravel(),
            np.asarray(y_external).ravel()
        ]).astype(int)
        group_all = np.array(
            ["Training set"] * int(len(y_train))
            + ["Test set"] * int(len(y_test))
            + ["External set"] * int(len(y_external)),
            dtype=object
        )
    else:
        if sp.issparse(X_train) or sp.issparse(X_test):
            X_all = sp.vstack([X_train, X_test], format="csr")
        else:
            X_all = np.vstack([np.asarray(X_train), np.asarray(X_test)])
        y_all = np.concatenate([np.asarray(y_train).ravel(), np.asarray(y_test).ravel()]).astype(int)
        group_all = np.array(["Training set"] * int(len(y_train)) + ["Test set"] * int(len(y_test)), dtype=object)

    outcome_all = np.where(y_all == 1, "M1", "M0")

    key_order = ["LR", "DT", "RF", "SVM", "KNN", "NB", "XGB", "SGBT", "NNET"]
    present = [k for k in key_order if k in importance_tables]
    present += [k for k in importance_tables.keys() if k not in present]

    for key in present:
        imp_df = importance_tables.get(key)
        if imp_df is None or imp_df.empty:
            continue

        p_tr = y_proba_train_by_model.get(key)
        p_te = y_proba_test_by_model.get(key)
        if p_tr is None or p_te is None:
            continue
        
        # Concatenate predicted probabilities
        if has_external and y_proba_external_by_model is not None:
            p_ex = y_proba_external_by_model.get(key)
            if p_ex is not None:
                p_all = np.concatenate([
                    np.asarray(p_tr).ravel(),
                    np.asarray(p_te).ravel(),
                    np.asarray(p_ex).ravel()
                ]).astype(float)
            else:
                p_all = np.concatenate([np.asarray(p_tr).ravel(), np.asarray(p_te).ravel()]).astype(float)
        else:
            p_all = np.concatenate([np.asarray(p_tr).ravel(), np.asarray(p_te).ravel()]).astype(float)

        sub = imp_df.copy()
        if "abs_importance" not in sub.columns:
            sub["abs_importance"] = sub["importance"].abs()
        sub = sub.sort_values("abs_importance", ascending=False)
        if top_n is not None:
            sub = sub.head(int(top_n))
        if "feature_idx" not in sub.columns:
            print(f"[FIG] {key}: missing feature_idx; skip variable heatmap.")
            continue

        feat_idx = sub["feature_idx"].astype(int).tolist()
        if "feature_display" in sub.columns:
            feat_labels = sub["feature_display"].astype(str).tolist()
        else:
            feat_labels = _clean_display_feature_names(sub["feature"].astype(str).tolist())

        # ---------- Build Feature Value Matrix ----------
        # Give priority to raw data (raw_df) to preserve authentic 0/1 values and original scales;
        # Fall back to the preprocessed matrix only when mapping fails.
        n_feat_tmp = len(feat_idx)
        n_samp_tmp = X_all.shape[0]
        feat_internals = sub["feature"].astype(str).tolist() if "feature" in sub.columns else [""] * n_feat_tmp
        raw_cols_list = list(raw_df.columns) if raw_df is not None else []

        vals = np.full((n_feat_tmp, n_samp_tmp), np.nan, dtype=float)
        for _fi in range(n_feat_tmp):
            mapped = False
            if raw_df is not None and len(raw_df) == n_samp_tmp:
                col_name, cat_val_str, is_cat = _parse_internal_feature_name(
                    feat_internals[_fi], raw_cols_list
                )
                if col_name is not None and col_name in raw_df.columns:
                    raw_v = raw_df[col_name].values
                    if is_cat and cat_val_str is not None:
                        # Revert One-hot: 1 = matches category, 0 = does not match
                        target = _convert_cat_val(cat_val_str)
                        nan_m = pd.isna(raw_v)
                        try:
                            matches = (raw_v == target)
                        except TypeError:
                            matches = (raw_v.astype(str) == str(target))
                        row_arr = np.where(matches, 1.0, 0.0)
                        if nan_m.any():
                            row_arr = row_arr.astype(float)
                            row_arr[nan_m] = np.nan
                        vals[_fi] = row_arr
                    else:
                        vals[_fi] = pd.to_numeric(raw_v, errors="coerce").astype(float)
                    mapped = True
            if not mapped:
                col_pp = X_all[:, feat_idx[_fi]]
                vals[_fi] = (
                    col_pp.toarray().ravel()
                    if sp.issparse(col_pp)
                    else np.asarray(col_pp).ravel()
                ).astype(float)

        # Min-max normalize each row into [0,1]
        row_min = np.nanmin(vals, axis=1, keepdims=True)
        row_max = np.nanmax(vals, axis=1, keepdims=True)
        den = np.where((row_max - row_min) == 0, 1.0, (row_max - row_min))
        vals01 = (vals - row_min) / den
        vals01 = np.clip(vals01, 0.0, 1.0)

        # Sort samples: Outcome → Group → Predicted probability (descending)
        # Encode group: Training=0, Test=1, External=2
        group_code_all = np.zeros(len(group_all), dtype=int)
        group_all_arr = np.asarray(group_all)
        group_code_all[group_all_arr == "Test set"] = 1
        group_code_all[group_all_arr == "External set"] = 2
        outcome_code_all = (y_all == 1).astype(int)  # M0=0, M1=1
        order = np.lexsort((-p_all, group_code_all, outcome_code_all))
        vals01 = vals01[:, order]
        vals_sorted = vals[:, order]
        p_sorted = p_all[order]
        outcome_sorted = outcome_all[order]
        group_sorted = group_all[order]
        group_code_sorted = group_code_all[order]
        outcome_code_sorted = outcome_code_all[order]

        n_feat = int(vals01.shape[0])
        n_samp = int(vals01.shape[1])

        def _fmt_tick(v: float) -> str:
            if not np.isfinite(v):
                return ""
            av = abs(float(v))
            if av >= 100:
                return f"{v:.0f}"
            if av >= 10:
                return f"{v:.1f}"
            return f"{v:.2f}"

        # Color schemes for sample plots - High contrast, distinct color configurations
        # Alternate brown, yellow, purple, pink, green, blue tones following the design template
        # Ensure high distinctiveness among adjacent items; avoid contiguous purple blocks
        example_colors = [
            "#C68642",  # Dark Brown-Orange
            "#F5C342",  # Golden Yellow
            "#2196F3",  # Bright Blue (Replaced dark purple to enhance contrast)
            "#E91E63",  # Rose Pink
            "#795548",  # Brown
            "#4CAF50",  # Green
            "#FF9800",  # Orange (Replaced indigo purple)
            "#9C27B0",  # Purple
            "#00BCD4",  # Cyan (Replaced purple to enhance contrast)
            "#8BC34A",  # Light Green (Replaced blue)
            "#FF5722",  # Deep Orange
            "#3F51B5",  # Indigo Blue
            "#CDDC39",  # Lime Green
            "#673AB7",  # Deep Purple
            "#009688",  # Deep Cyan
            "#E040FB",  # Bright Violet
            "#FF6F00",  # Amber
            "#1E88E5",  # Light Blue
            "#43A047",  # Dark Green
            "#F06292",  # Soft Pink
            "#7E57C2",  # Medium Violet
            "#26A69A",  # Medium Teal
            "#FFA000",  # Dark Yellow
            "#5E35B1",  # Dark Indigo
        ]
        # Expand color lists to safely encapsulate all features
        base_colors = []
        for i in range(n_feat):
            base_colors.append(matplotlib.colors.to_rgba(example_colors[i % len(example_colors)]))

        # Categorical variable 0-value uses light gray-beige instead of white, adhering to style templates
        light_rgba = matplotlib.colors.to_rgba("#F5F5DC")  # Light Beige-Gray
        rgba = np.zeros((n_feat, n_samp, 4), dtype=float)
        row_cm: list[Any] = []
        row_ticks: list[tuple[list[float], list[str]]] = []
        row_min_max: list[tuple[float, float]] = []

        for i in range(n_feat):
            v_raw = np.asarray(vals_sorted[i, :], dtype=float)
            v01 = np.asarray(vals01[i, :], dtype=float)
            v_raw_finite = v_raw[np.isfinite(v_raw)]
            uniq = np.unique(v_raw_finite) if v_raw_finite.size else np.array([])
            base_rgba = base_colors[i]

            mn = float(np.nanmin(v_raw_finite)) if v_raw_finite.size else 0.0
            mx = float(np.nanmax(v_raw_finite)) if v_raw_finite.size else 1.0
            row_min_max.append((mn, mx))

            # Determine whether discrete or continuous
            is_binary_exact = uniq.size <= 2 and uniq.size > 0 and np.all(np.isin(uniq, [0.0, 1.0]))
            is_binary_any2 = uniq.size == 2
            is_binary01 = is_binary_exact or is_binary_any2
            is_small_discrete = (not is_binary01) and (uniq.size > 0) and (uniq.size <= 3)

            if is_binary01:
                if uniq.size >= 2:
                    high_val = uniq[-1]
                else:
                    high_val = 1.0
                mask1 = np.isclose(v_raw, high_val)
                rgba[i, :, :] = light_rgba
                rgba[i, mask1, :] = base_rgba
                row_cm.append(matplotlib.colors.ListedColormap([light_rgba, base_rgba]))
                row_ticks.append(([0, 1], ["0", "1"]))
            elif is_small_discrete:
                levels = np.sort(uniq)
                colors = [light_rgba]
                for t in np.linspace(0.45, 1.0, num=int(levels.size) - 1):
                    c = (
                        light_rgba[0] * (1 - t) + base_rgba[0] * t,
                        light_rgba[1] * (1 - t) + base_rgba[1] * t,
                        light_rgba[2] * (1 - t) + base_rgba[2] * t,
                        1.0,
                    )
                    colors.append(c)
                cm = matplotlib.colors.ListedColormap(colors)
                rgba[i, :, :] = light_rgba
                for j, lv in enumerate(levels):
                    mask = np.isclose(v_raw, lv)
                    rgba[i, mask, :] = colors[min(j, len(colors) - 1)]
                row_cm.append(cm)
                row_ticks.append((list(range(int(levels.size))), [_fmt_tick(lv) for lv in levels]))
            else:
                cm = matplotlib.colors.LinearSegmentedColormap.from_list(
                    "row", [light_rgba, base_rgba]
                )
                rgba[i, :, :] = cm(np.clip(v01, 0.0, 1.0))
                row_cm.append(cm)
                row_ticks.append(([0, 1], [_fmt_tick(mn), _fmt_tick(mx)]))

        # ============ Layout Design ============
        # Legend section: A single vertical colorbar for each variable, fixed at 6 columns per row
        legend_ncol = 6  
        n_legend_items = n_feat + 3  # Features + predicted value + outcome + group
        legend_nrows = int(math.ceil(n_legend_items / legend_ncol))

        # Figure Dimensions - fine tuning legend space allocation
        fig_w = max(10.0, n_samp / 100.0)
        heatmap_h = 0.28 * n_feat
        annot_h = 0.3 * 3  # 3 annotation rows (compacted height)
        legend_h = 1.8 * legend_nrows  # Row height (more compact)
        fig_h = heatmap_h + annot_h + legend_h + 4.0  # Margin allocation for bottom empty spaces

        fig = plt.figure(figsize=(fig_w, fig_h), facecolor="white")
        # Global grid definition: Heatmap | 3 Annotation rows | Spacing block | Legend block
        # Annotation height parameters strictly align with variable rows (each 1.0), hspace=0 ensures clean stacking
        gs_main = fig.add_gridspec(
            6, 1,
            height_ratios=[n_feat, 1.0, 1.0, 1.0, 1.2, legend_nrows * 3.5 + 2.0],  
            hspace=0.0,
            top=0.96, bottom=0.04, left=0.02, right=0.88
        )

        # ============ Main Heatmap Panel ============
        ax0 = fig.add_subplot(gs_main[0, 0])
        ax0.imshow(rgba, aspect="auto", interpolation="nearest")
        ax0.set_yticks(np.arange(n_feat))
        ax0.set_yticklabels([])  # Hide left-side ticks
        ax0.set_xticks([])
        ax0.tick_params(left=False, bottom=False)
        for spine in ax0.spines.values():
            spine.set_visible(False)
        # Append thin horizontal divider grid lines
        for i in range(1, n_feat):
            ax0.axhline(y=i - 0.5, color="white", linewidth=0.5)

        # Right labels - upscale font metrics
        ax0_right = ax0.secondary_yaxis("right")
        ax0_right.set_yticks(np.arange(n_feat))
        ax0_right.set_yticklabels(feat_labels, fontsize=FONTSIZE_FEATURE_LABEL)
        ax0_right.tick_params(right=False)
        # Suppress bounding borders on right side axes to prevent solid dark edges
        for spine in ax0_right.spines.values():
            spine.set_visible(False)

        # ============ RF Predicted Value (Solid stripe presentation, non-gradated) ============
        ax1 = fig.add_subplot(gs_main[1, 0], sharex=ax0)
        # Standardize using a brown-orange gradient mapping scheme matching benchmark charts
        pred_cmap = matplotlib.colors.LinearSegmentedColormap.from_list("pred", ["#FFF5E6", "#D2691E"])
        # Map probabilistic profiles natively across the block arrays without smoothing interpolation
        ax1.imshow(p_sorted.reshape(1, -1), aspect="auto", interpolation="none", cmap=pred_cmap, vmin=0.0, vmax=1.0)
        ax1.set_yticks([])
        ax1.set_xticks([])
        for spine in ax1.spines.values():
            spine.set_visible(False)
        # Top segment delimiter setup
        ax1.axhline(y=-0.5, color="white", linewidth=0.5)
        ax1_right = ax1.secondary_yaxis("right")
        ax1_right.set_yticks([0])
        ax1_right.set_yticklabels([f"{key} predicted value"], fontsize=FONTSIZE_ANNOT_LABEL)
        ax1_right.tick_params(right=False)
        for spine in ax1_right.spines.values():
            spine.set_visible(False)

        # ============ Outcome Panel ============
        ax2 = fig.add_subplot(gs_main[2, 0], sharex=ax0)
        outcome_code = outcome_code_sorted
        outcome_cmap = matplotlib.colors.ListedColormap(["#8BC34A", "#FF9800"])  # M0 Green, M1 Orange
        ax2.imshow(outcome_code.reshape(1, -1), aspect="auto", interpolation="none", cmap=outcome_cmap, vmin=0, vmax=1)
        ax2.set_yticks([])
        ax2.set_xticks([])
        for spine in ax2.spines.values():
            spine.set_visible(False)
        ax2.axhline(y=-0.5, color="white", linewidth=0.5)
        ax2_right = ax2.secondary_yaxis("right")
        ax2_right.set_yticks([0])
        ax2_right.set_yticklabels(["Outcome"], fontsize=FONTSIZE_ANNOT_LABEL)
        ax2_right.tick_params(right=False)
        for spine in ax2_right.spines.values():
            spine.set_visible(False)

        # ============ Group Panel (Handles 3 states: Training/Test/External validation blocks) ============
        ax3 = fig.add_subplot(gs_main[3, 0], sharex=ax0)
        group_code = group_code_sorted
        # Tri-color code parameters: Training Purple, Test Orange, External Cyan
        group_cmap = matplotlib.colors.ListedColormap(["#9C27B0", "#FF9800", "#00BCD4"])
        n_groups = 3 if has_external else 2
        ax3.imshow(group_code.reshape(1, -1), aspect="auto", interpolation="none", cmap=group_cmap, vmin=0, vmax=n_groups - 1)
        ax3.set_yticks([])
        ax3.set_xticks([])
        for spine in ax3.spines.values():
            spine.set_visible(False)
        ax3.axhline(y=-0.5, color="white", linewidth=0.5)
        ax3_right = ax3.secondary_yaxis("right")
        ax3_right.set_yticks([0])
        ax3_right.set_yticklabels(["Group"], fontsize=FONTSIZE_ANNOT_LABEL)
        ax3_right.tick_params(right=False)
        for spine in ax3_right.spines.values():
            spine.set_visible(False)

        # ============ Bottom Legend Panel ============
        # Insert empty spacer grid layer (gs_main[4, 0]), then load subgridspec arrays for legends
        gs_legend = gs_main[5, 0].subgridspec(legend_nrows, legend_ncol, wspace=0.18, hspace=0.40)  

        # Assemble global metadata dictionaries for legend blocks
        legend_items = []
        for i in range(n_feat):
            ticks = row_ticks[i]
            if ticks[1] == ["0", "1"]:
                ltype = "binary"
            elif len(ticks[0]) <= 2:
                ltype = "continuous"
            else:
                ltype = "discrete"
            legend_items.append({
                "type": ltype,
                "label": feat_labels[i],
                "cmap": row_cm[i],
                "ticks": ticks,
                "vmin": row_min_max[i][0],
                "vmax": row_min_max[i][1],
                "base_color": base_colors[i],
            })
        # Model predicted values - handled via gradated format containing explicit boundaries
        legend_items.append({
            "type": "continuous",
            "label": f"{key} predicted value",
            "cmap": pred_cmap,
            "ticks": ([0, 0.5, 1], ["0", "0.5", "1"]),
            "vmin": 0, "vmax": 1,
            "base_color": matplotlib.colors.to_rgba("#D2691E"),
        })
        # Outcome definitions
        legend_items.append({
            "type": "categorical",
            "label": "Outcome",
            "colors": ["#8BC34A", "#FF9800"],
            "labels": ["M0", "M1"],
        })
        # Group definitions (Dynamically structured according to external data trace inputs)
        if has_external:
            legend_items.append({
                "type": "categorical",
                "label": "Group",
                "colors": ["#9C27B0", "#FF9800", "#00BCD4"],
                "labels": ["Training set", "Test set", "External set"],
            })
        else:
            legend_items.append({
                "type": "categorical",
                "label": "Group",
                "colors": ["#9C27B0", "#FF9800"],
                "labels": ["Training set", "Test set"],
            })

        for idx, item in enumerate(legend_items):
            row = idx // legend_ncol
            col = idx % legend_ncol
            if row >= legend_nrows:
                break
            ax_leg = fig.add_subplot(gs_legend[row, col])

            # Standarize Y-axis limits across all items to guarantee that title text lines up perfectly across a row
            unified_ylim = (-0.1, 1.15)
            unified_xlim = (-0.05, 1.3)
            
            # Formulate box_w parameters responsively to achieve perfect square blocks for color blocks
            # Formula: box_w = box_h * (ax_height / ax_width) * (xlim_range / ylim_range)
            fig.canvas.draw()  # Pre-render required to draw spatial layouts natively
            ax_pos = ax_leg.get_position()
            ax_width = ax_pos.width * fig.get_figwidth()   # axes physical width (inches)
            ax_height = ax_pos.height * fig.get_figheight()  # axes physical height (inches)
            xlim_range = unified_xlim[1] - unified_xlim[0]  # 1.35
            ylim_range = unified_ylim[1] - unified_ylim[0]  # 1.25
            
            box_h = 0.3  # Box block element height dimension matching native coordinates
            if ax_width > 0:
                box_w = box_h * (ax_height / ax_width) * (xlim_range / ylim_range)
            else:
                box_w = box_h  # fallback

            if item["type"] == "categorical":
                # Discrete configurations: Arrange color patches vertically, top-aligned
                n_cats = len(item["colors"])
                top_y = 1.0  
                for j, (color, label) in enumerate(zip(item["colors"], item["labels"])):
                    y_pos = top_y - (j + 1) * box_h  
                    rect = plt.Rectangle((0, y_pos), box_w, box_h * 0.9, facecolor=color, edgecolor="none")
                    ax_leg.add_patch(rect)
                    ax_leg.text(box_w + 0.06, y_pos + box_h * 0.45, label, ha="left", va="center", fontsize=FONTSIZE_LEGEND_TEXT)
                ax_leg.set_xlim(unified_xlim)
                ax_leg.set_ylim(unified_ylim)
            elif item["type"] == "binary":
                # Binary configurations: Stack two square patches vertically, top-aligned
                cm = item["cmap"]
                colors = [cm(0.0), cm(1.0)]
                labels = item["ticks"][1]
                top_y = 1.0  
                for j, (color, label) in enumerate(zip(colors, labels)):
                    y_pos = top_y - (j + 1) * box_h  
                    rect = plt.Rectangle((0, y_pos), box_w, box_h * 0.9, facecolor=color, edgecolor="none")
                    ax_leg.add_patch(rect)
                    ax_leg.text(box_w + 0.06, y_pos + box_h * 0.45, label, ha="left", va="center", fontsize=FONTSIZE_LEGEND_TEXT)
                ax_leg.set_xlim(unified_xlim)
                ax_leg.set_ylim(unified_ylim)
            else:
                # Continuous spectrum configurations: Vertical scale bars with ticks
                gradient = np.linspace(0, 1, 256).reshape(-1, 1)
                ax_leg.imshow(gradient, aspect="auto", cmap=item["cmap"], origin="lower", extent=[0, 0.22, 0, 1])
                vmin, vmax = item["vmin"], item["vmax"]
                if vmax - vmin > 0:
                    n_ticks = 4
                    tick_vals = np.linspace(vmin, vmax, n_ticks)
                    tick_positions = np.linspace(0, 1, n_ticks)
                else:
                    tick_vals = [vmin]
                    tick_positions = [0.5]
                # Map specific tick text elements safely onto layouts
                for tv, tp in zip(tick_vals, tick_positions):
                    ax_leg.plot([0.24, 0.28], [tp, tp], color="0.3", linewidth=0.8)
                    ax_leg.text(0.32, tp, _fmt_tick(tv), ha="left", va="center", fontsize=FONTSIZE_COLORBAR_TICK)
                ax_leg.set_xlim(unified_xlim)
                ax_leg.set_ylim(unified_ylim)

            ax_leg.set_xticks([])
            ax_leg.set_yticks([])
            for spine in ax_leg.spines.values():
                spine.set_visible(False)
            # Title alignments - left justified using identical shade indices
            if item["type"] == "categorical":
                title_color = item["colors"][0]
            else:
                title_color = matplotlib.colors.to_hex(item["base_color"])
            # Mount titles securely on predefined standardized peak-ceil lines
            ax_leg.text(0, unified_ylim[1] + 0.05, item["label"], fontsize=FONTSIZE_LEGEND_TITLE, fontweight="bold", 
                        color=title_color, ha="left", va="bottom")

        plt.setp(ax0.get_xticklabels(), visible=False)
        out_path = out_dir / f"Variable_heatmap_{key}.png"
        fig.savefig(out_path, dpi=300, facecolor="white", bbox_inches="tight")
        plt.close(fig)
        print(f"  -> {key} Heatmap saved: {out_path}")


# ============ Main Execution Function ============
def main():
    # Fallback executing dictionary directory
    DEFAULT_RUN_DIR = "ml_results/run_20260206_234650"
    
    parser = argparse.ArgumentParser(description="Redraw Variable Heatmap (Direct reuse of functions from original file)")
    parser.add_argument("--run_dir", default=DEFAULT_RUN_DIR, 
                        help=f"Path to executed result directory (Default: {DEFAULT_RUN_DIR})")
    parser.add_argument("--target", default="Metastasis", help="Dependent variable column name")
    parser.add_argument("--top_n", type=int, default=20, help="Number of features to display (Default: 20, consistent with original execution)")
    parser.add_argument("--models", default=None, help="Target models (comma-separated, e.g., LR,RF,XGB), None renders all available models")
    parser.add_argument("--output_dir", default=None, help="Output folder target (Defaults to run_dir/fig_new)")
    args = parser.parse_args()

    run_dir = Path(args.run_dir)
    if not run_dir.exists():
        raise FileNotFoundError(f"Cannot locate run directory: {run_dir}")

    # Configure destination output arrays
    output_dir = Path(args.output_dir) if args.output_dir else run_dir / "fig_new"
    _ensure_dir(output_dir)

    # Initialize processor artifact imports
    preprocessor_path = run_dir / "artifacts" / "preprocessor.joblib"
    if not preprocessor_path.exists():
        raise FileNotFoundError(f"Cannot locate preprocessor file: {preprocessor_path}")
    preprocessor = joblib.load(preprocessor_path)

    # Extract workbook partitioned data matrices
    train_xlsx = run_dir / "tables" / "split_train.xlsx"
    test_xlsx = run_dir / "tables" / "split_test.xlsx"
    
    if not (train_xlsx.exists() and test_xlsx.exists()):
        raise FileNotFoundError("Missing training or test excel partition targets.")
    
    df_train = pd.read_excel(train_xlsx)
    df_test = pd.read_excel(test_xlsx)
    
    # Identify target columns to purge
    cols_to_drop = [args.target] + [c for c in DEMOGRAPHIC_COLUMNS_EXCLUDE if c in df_train.columns]
    
    y_train = df_train[args.target].astype(int).to_numpy()
    y_test = df_test[args.target].astype(int).to_numpy()
    X_train_df = df_train.drop(columns=[c for c in cols_to_drop if c in df_train.columns])
    X_test_df = df_test.drop(columns=[c for c in cols_to_drop if c in df_test.columns])

    X_train = _safe_float32_matrix(preprocessor.transform(X_train_df))
    X_test = _safe_float32_matrix(preprocessor.transform(X_test_df))

    print(f"Training subset: {len(y_train)} samples")
    print(f"Test subset: {len(y_test)} samples")

    # Evaluate validation structures
    external_xlsx = run_dir / "tables" / "split_external.xlsx"
    has_external = external_xlsx.exists()
    X_external = None
    y_external = None
    
    if has_external:
        df_ext = pd.read_excel(external_xlsx)
        y_external = df_ext[args.target].astype(int).to_numpy()
        X_ext_df = df_ext.drop(columns=[c for c in cols_to_drop if c in df_ext.columns])
        # Align column indexes
        for col in X_train_df.columns:
            if col not in X_ext_df.columns:
                X_ext_df[col] = np.nan
        X_ext_df = X_ext_df[X_train_df.columns]  # Enforce row/column matching bounds
        X_external = _safe_float32_matrix(preprocessor.transform(X_ext_df))
        print(f"External validation subset: {len(y_external)} samples")

    # Find valid models
    model_files = list((run_dir / "artifacts").glob("model_*.joblib"))
    available_models = [p.stem.replace("model_", "") for p in model_files]
    print(f"Available models: {available_models}")

    # Filter pipeline operations
    if args.models:
        selected_models = [m.strip() for m in args.models.split(",")]
        selected_models = [m for m in selected_models if m in available_models]
    else:
        selected_models = available_models

    if not selected_models:
        print("No match found for targeted visualization processing.")
        return

    # Parse and register core structures
    fitted_pipelines: dict[str, Any] = {}
    importance_tables: dict[str, pd.DataFrame] = {}
    
    for model_key in selected_models:
        print(f"\n[{model_key}] Importing model metadata and feature importance distributions...")
        
        # Load serialized pipeline models
        model_path = run_dir / "artifacts" / f"model_{model_key}.joblib"
        try:
            model = joblib.load(model_path)
            fitted_pipelines[model_key] = model
        except Exception as e:
            print(f"  Warning: Unable to load model parameter tracking at {model_path}, skipping.")
            print(f"  Error trace: {e}")
            continue
        
        # Import related tabular parameters
        imp_path = run_dir / "tables" / f"feature_importance_{model_key}.csv"
        if not imp_path.exists():
            print(f"  Warning: Cannot locate feature metrics table at {imp_path}, skipping.")
            continue
        
        imp_df = pd.read_csv(imp_path)
        importance_tables[model_key] = imp_df
        print(f"  -> Imported successfully")

    if not fitted_pipelines:
        print("No computational pipelines were loaded successfully.")
        return

    # Generate forward predictions
    print("\nCalculating prediction probabilities...")
    y_proba_train_by_model: dict[str, np.ndarray] = {}
    y_proba_test_by_model: dict[str, np.ndarray] = {}
    y_proba_external_by_model: dict[str, np.ndarray] = {}

    for model_key, model in fitted_pipelines.items():
        try:
            p_train = model.predict_proba(X_train)[:, 1]
            p_test = model.predict_proba(X_test)[:, 1]
            y_proba_train_by_model[model_key] = p_train
            y_proba_test_by_model[model_key] = p_test
            
            if has_external and X_external is not None:
                p_external = model.predict_proba(X_external)[:, 1]
                y_proba_external_by_model[model_key] = p_external
            
            print(f"  [{model_key}] Inference complete")
        except Exception as e:
            print(f"  [{model_key}] Inference execution failed: {e}")
            # Erase error-prone targets safely
            if model_key in importance_tables:
                del importance_tables[model_key]

    # Filter out models that failed prediction
    valid_models = set(y_proba_train_by_model.keys()) & set(importance_tables.keys())
    importance_tables = {k: v for k, v in importance_tables.items() if k in valid_models}

    if not importance_tables:
        print("No valid models are available for plot mapping.")
        return

    # Concatenate raw data elements sequentially (maintaining explicit alignment with processing steps) for visualization
    raw_dfs = [X_train_df, X_test_df]
    if has_external:
        raw_dfs.append(X_ext_df)
    raw_df_concat = pd.concat(raw_dfs, ignore_index=True)

    # Invoke mapping visualizations
    print(f"\nInitializing heatmap plotting pipeline...")
    print(f"Destination folder path: {output_dir}")
    
    save_variable_heatmaps_by_model(
        out_dir=output_dir,
        X_train=X_train,
        X_test=X_test,
        y_train=y_train,
        y_test=y_test,
        y_proba_train_by_model=y_proba_train_by_model,
        y_proba_test_by_model=y_proba_test_by_model,
        importance_tables=importance_tables,
        top_n=args.top_n,
        X_external=X_external if has_external else None,
        y_external=y_external if has_external else None,
        y_proba_external_by_model=y_proba_external_by_model if has_external else None,
        raw_df=raw_df_concat,
    )

    print(f"\nExecution finished! Saved to: {output_dir}")


if __name__ == "__main__":
    main()